"""Mock booking data, in Python, mirroring src/data/mock-bookings.ts.

When the TypeScript source changes, regenerate this file too — or run the
PDF generator and accept the drift.
"""

DEMO_AGENCY = {
    "name": "Travelaire Holidays",
    "phone": "+44 121 555 8800",
    "email": "hello@travelaire.co.uk",
    "emergencyPhone": "+44 7700 900900",
    "website": "travelaire.co.uk",
    "atolNumber": "ATOL 12345",
}

BOOKINGS = [
    # Maldives — Swan family
    {
        "reference": "DEMO81297",
        "destinationLabel": "Maldives",
        "tripStart": "2026-11-27",
        "tripEnd": "2026-12-04",
        "durationLabel": "7 nights",
        "leadEmail": "darren.swan@example.com",
        "travellers": [
            {"title": "Mr", "firstName": "Darren", "lastName": "Swan", "type": "adult", "isLead": True, "nationality": "GB"},
            {"title": "Mrs", "firstName": "Sarah", "lastName": "Swan", "type": "adult", "isLead": False, "nationality": "GB"},
            {"title": "Master", "firstName": "Ethan", "lastName": "Swan", "type": "child", "age": 11, "isLead": False, "nationality": "GB"},
            {"title": "Miss", "firstName": "Lily", "lastName": "Swan", "type": "child", "age": 9, "isLead": False, "nationality": "GB"},
        ],
        "flights": [
            {"flightNumber": "EY20", "carrier": "Etihad Airways", "cabin": "Economy",
             "depAirport": "LGW", "depAirportName": "London Gatwick", "depTerminal": "South",
             "depDate": "Fri 27 Nov 2026", "depTime": "20:15",
             "arrAirport": "AUH", "arrAirportName": "Abu Dhabi International",
             "arrDate": "Sat 28 Nov 2026", "arrTime": "07:25",
             "duration": "7h 10m", "aircraft": "B787-9", "baggage": "23kg checked + 7kg cabin",
             "pnr": "PQR4X9",
             "seats": {"Mr Darren Swan": "14A", "Mrs Sarah Swan": "14B", "Master Ethan Swan": "14C", "Miss Lily Swan": "14D"}},
            {"flightNumber": "EY278", "carrier": "Etihad Airways", "cabin": "Economy",
             "depAirport": "AUH", "depAirportName": "Abu Dhabi International", "depTerminal": "",
             "depDate": "Sat 28 Nov 2026", "depTime": "10:00",
             "arrAirport": "MLE", "arrAirportName": "Velana International",
             "arrDate": "Sat 28 Nov 2026", "arrTime": "12:55",
             "duration": "2h 55m", "aircraft": "A320", "baggage": "23kg checked + 7kg cabin",
             "pnr": "PQR4X9",
             "seats": {"Mr Darren Swan": "8A", "Mrs Sarah Swan": "8B", "Master Ethan Swan": "8C", "Miss Lily Swan": "8D"}},
            {"flightNumber": "EY279", "carrier": "Etihad Airways", "cabin": "Economy",
             "depAirport": "MLE", "depAirportName": "Velana International", "depTerminal": "",
             "depDate": "Fri 4 Dec 2026", "depTime": "14:30",
             "arrAirport": "AUH", "arrAirportName": "Abu Dhabi International",
             "arrDate": "Fri 4 Dec 2026", "arrTime": "18:05",
             "duration": "3h 35m", "aircraft": "A320", "baggage": "23kg checked + 7kg cabin",
             "pnr": "PQR4X9", "seats": {}},
            {"flightNumber": "EY11", "carrier": "Etihad Airways", "cabin": "Economy",
             "depAirport": "AUH", "depAirportName": "Abu Dhabi International", "depTerminal": "",
             "depDate": "Fri 4 Dec 2026", "depTime": "21:15",
             "arrAirport": "LGW", "arrAirportName": "London Gatwick",
             "arrDate": "Sat 5 Dec 2026", "arrTime": "02:25",
             "duration": "5h 10m", "aircraft": "B787-9", "baggage": "23kg checked + 7kg cabin",
             "pnr": "PQR4X9", "seats": {}},
        ],
        "hotels": [
            {"name": "Avyanna Gulhi Beach Hotel", "stars": 4,
             "address": "Gulhi Island, South Malé Atoll, Maldives",
             "checkIn": "Sat 28 Nov 2026 · 15:00",
             "checkOut": "Fri 4 Dec 2026 · 11:00",
             "nights": 6, "room": "8 Bed Mixed Dorm", "board": "Bed & breakfast",
             "ref": "AVY-GLH-887412",
             "specialRequests": "Twin room preferred. Late check-in noted with hotel. Cot not required."},
        ],
        "airportExtras": [
            {"name": "No1 Lounge South Terminal", "type": "Airport lounge", "airport": "LGW",
             "date": "Fri 27 Nov 2026", "time": "17:00", "guests": 4,
             "notes": "3-hour pre-departure access. Show this voucher with booking ref at reception."},
        ],
        "atol": True,
        "insurance": True,
        "payment": {"currency": "GBP", "total": "6240.00", "deposit": "1248.00", "balance": "0.00", "balanceDueDate": "15 Sep 2026"},
    },
    # Mallorca — Watson family
    {
        "reference": "DEMO74002",
        "destinationLabel": "Mallorca",
        "tripStart": "2026-07-22",
        "tripEnd": "2026-08-01",
        "durationLabel": "10 days · 10 nights",
        "leadEmail": "helen.watson@example.com",
        "travellers": [
            {"title": "Mrs", "firstName": "Helen", "lastName": "Watson", "type": "adult", "isLead": True, "nationality": "GB"},
            {"title": "Mr", "firstName": "Paul", "lastName": "Watson", "type": "adult", "isLead": False, "nationality": "GB"},
            {"title": "Miss", "firstName": "Grace", "lastName": "Watson", "type": "child", "age": 8, "isLead": False, "nationality": "GB"},
            {"title": "Master", "firstName": "Theo", "lastName": "Watson", "type": "child", "age": 6, "isLead": False, "nationality": "GB"},
        ],
        "flights": [
            {"flightNumber": "LS835", "carrier": "Jet2", "cabin": "Economy",
             "depAirport": "BHX", "depAirportName": "Birmingham", "depTerminal": "",
             "depDate": "Wed 22 Jul 2026", "depTime": "06:15",
             "arrAirport": "PMI", "arrAirportName": "Palma de Mallorca",
             "arrDate": "Wed 22 Jul 2026", "arrTime": "10:05",
             "duration": "2h 50m", "aircraft": "B737-800", "baggage": "22kg checked + 10kg cabin",
             "pnr": "LSGH88",
             "seats": {"Mrs Helen Watson": "12C", "Mr Paul Watson": "12D", "Miss Grace Watson": "12E", "Master Theo Watson": "12F"}},
            {"flightNumber": "LS836", "carrier": "Jet2", "cabin": "Economy",
             "depAirport": "PMI", "depAirportName": "Palma de Mallorca", "depTerminal": "",
             "depDate": "Sat 1 Aug 2026", "depTime": "19:20",
             "arrAirport": "BHX", "arrAirportName": "Birmingham",
             "arrDate": "Sat 1 Aug 2026", "arrTime": "22:40",
             "duration": "2h 55m", "aircraft": "B737-800", "baggage": "22kg checked + 10kg cabin",
             "pnr": "LSGH88", "seats": {}},
        ],
        "hotels": [
            {"name": "Iberostar Selection Playa de Muro Village", "stars": 4,
             "address": "Playa de Muro, Alcúdia, North Mallorca, Spain",
             "checkIn": "Wed 22 Jul 2026 · 15:00",
             "checkOut": "Sat 1 Aug 2026 · 11:00",
             "nights": 10, "room": "Family Junior Suite Garden View", "board": "All inclusive",
             "ref": "IBE-PDM-552901",
             "specialRequests": "Cot for Theo. Family room close to kids club preferred."},
        ],
        "airportExtras": [
            {"name": "BHX Express Parking", "type": "Airport parking", "airport": "BHX",
             "date": "Wed 22 Jul 2026", "time": "04:00", "guests": None,
             "notes": "10 days · Bay 14B. Drive directly to the bay; keys stay with you."},
            {"name": "Security Fast Track", "type": "Security fast track", "airport": "BHX",
             "date": "Wed 22 Jul 2026", "time": "04:30", "guests": 4,
             "notes": "Show this voucher at the fast track entrance. Valid for the named party."},
        ],
        "atol": True,
        "insurance": False,
        "payment": {"currency": "GBP", "total": "4180.00", "deposit": "836.00", "balance": "3344.00", "balanceDueDate": "8 Jun 2026"},
    },
    # Dubai — Patel couple
    {
        "reference": "DEMO66541",
        "destinationLabel": "Dubai",
        "tripStart": "2026-10-05",
        "tripEnd": "2026-10-12",
        "durationLabel": "5 nights",
        "leadEmail": "priya.patel@example.com",
        "travellers": [
            {"title": "Mrs", "firstName": "Priya", "lastName": "Patel", "type": "adult", "isLead": True, "nationality": "GB"},
            {"title": "Mr", "firstName": "Raj", "lastName": "Patel", "type": "adult", "isLead": False, "nationality": "GB"},
        ],
        "flights": [
            {"flightNumber": "EK4", "carrier": "Emirates", "cabin": "Business",
             "depAirport": "LHR", "depAirportName": "London Heathrow", "depTerminal": "3",
             "depDate": "Mon 5 Oct 2026", "depTime": "22:30",
             "arrAirport": "DXB", "arrAirportName": "Dubai International",
             "arrDate": "Tue 6 Oct 2026", "arrTime": "09:05",
             "duration": "6h 55m", "aircraft": "A380-800", "baggage": "40kg checked + 7kg cabin",
             "pnr": "EK77JN",
             "seats": {"Mrs Priya Patel": "14A", "Mr Raj Patel": "14K"}},
            {"flightNumber": "EK1", "carrier": "Emirates", "cabin": "Business",
             "depAirport": "DXB", "depAirportName": "Dubai International", "depTerminal": "3",
             "depDate": "Mon 12 Oct 2026", "depTime": "08:30",
             "arrAirport": "LHR", "arrAirportName": "London Heathrow",
             "arrDate": "Mon 12 Oct 2026", "arrTime": "13:15",
             "duration": "6h 45m", "aircraft": "A380-800", "baggage": "40kg checked + 7kg cabin",
             "pnr": "EK77JN", "seats": {}},
        ],
        "hotels": [
            {"name": "Atlantis, The Palm", "stars": 5,
             "address": "Palm Jumeirah, Dubai, United Arab Emirates",
             "checkIn": "Tue 6 Oct 2026 · 15:00",
             "checkOut": "Fri 9 Oct 2026 · 12:00",
             "nights": 3, "room": "Ocean Deluxe King Room", "board": "Bed & breakfast",
             "ref": "ATL-PLM-339920",
             "specialRequests": "High floor · away from lift."},
            {"name": "Burj Al Arab Jumeirah", "stars": 5,
             "address": "Jumeirah Beach, Dubai, United Arab Emirates",
             "checkIn": "Fri 9 Oct 2026 · 15:00",
             "checkOut": "Mon 12 Oct 2026 · 05:00",
             "nights": 2, "room": "Deluxe Two Bedroom Suite", "board": "Half board",
             "ref": "BAJ-JMR-771403",
             "specialRequests": "Anniversary stay — please advise hotel."},
        ],
        "airportExtras": [
            {"name": "Plaza Premium Lounge", "type": "Airport lounge", "airport": "LHR",
             "date": "Mon 5 Oct 2026", "time": "20:00", "guests": 2,
             "notes": "3-hour pre-departure access at Terminal 3."},
            {"name": "Security Fast Track", "type": "Security fast track", "airport": "LHR",
             "date": "Mon 5 Oct 2026", "time": "20:30", "guests": 2,
             "notes": "Show voucher at Terminal 3 fast track entrance."},
        ],
        "atol": True,
        "insurance": True,
        "payment": {"currency": "GBP", "total": "11280.00", "deposit": "2256.00", "balance": "0.00", "balanceDueDate": "8 Aug 2026"},
    },
    # Athens — Mitchell solo
    {
        "reference": "DEMO52188",
        "destinationLabel": "Athens",
        "tripStart": "2026-09-18",
        "tripEnd": "2026-09-21",
        "durationLabel": "3 nights",
        "leadEmail": "james.mitchell@example.com",
        "travellers": [
            {"title": "Mr", "firstName": "James", "lastName": "Mitchell", "type": "adult", "isLead": True, "nationality": "GB"},
        ],
        "flights": [],
        "hotels": [
            {"name": "Electra Metropolis Athens", "stars": 5,
             "address": "Plaka, Athens, Greece",
             "checkIn": "Fri 18 Sep 2026 · 15:00",
             "checkOut": "Mon 21 Sep 2026 · 11:00",
             "nights": 3, "room": "Deluxe Acropolis View King Room", "board": "Bed & breakfast",
             "ref": "ELE-MET-449117",
             "specialRequests": "Acropolis view confirmed at booking."},
        ],
        "airportExtras": [],
        "atol": False,
        "insurance": False,
        "payment": {"currency": "GBP", "total": "980.00", "deposit": "196.00", "balance": "0.00", "balanceDueDate": "25 Jul 2026"},
    },
]
